name: aso-sample

vmSize: Standard_B2s
vmComputerName: poppy
vmAdminUsername: userAdmin
vmPassword: Password123%
armRegionName: westus3
resourceGroupName: aso-sample-rg

global:
  tableName: finops

portal:
  enabled: true
  card:
    icon: fa-cubes
  overview:
    enabled: true
    text: Example Pricing of a VM on Azure
  compositionstatus:
    enabled: true
  applicationstatus:
    enabled: true
  terminal:
    enabled: false
  events:
    enabled: true
  yamlviewer:
    enabled: true
  finops:
    enabled: true