{{- if not (lookup "resources.azure.com/v1api20200601" "ResourceGroup" .Release.Namespace .values.resourceGroupName ) -}}
apiVersion: resources.azure.com/v1api20200601
kind: ResourceGroup
metadata:
  name: {{ .Values.resourceGroupName }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  location: {{ .Values.armRegionName }}
{{ end }}