apiVersion: v1
kind: Secret
metadata:
  name: {{ include "example-pricing-vm-azure.fullname" . }}
type: opaque
stringData:
  password: {{ .Values.vmPassword }}
---
apiVersion: v1
kind: Secret
metadata: 
  name: azure-management-api
  namespace: {{ .Values.global.krateoNamespace }}
stringData:
  server-url: https://management.azure.com
