apiVersion: v1
data:
  drawer: "true"
  form: "true"
  showFormStructure: "true"
  drawerSize: large
kind: ConfigMap
metadata:
  name: template-finops-example-pricing-vm-azure-card
  namespace: azure-pricing-system
---
apiVersion: templates.krateo.io/v1alpha1
kind: Widget
metadata:
  name: template-finops-example-pricing-vm-azure-card
  namespace: azure-pricing-system
spec:
  actions:
  - template:
      apiVersion: templates.krateo.io/v1alpha1
      name: template-finops-example-pricing-vm-azure-customform
      namespace: azure-pricing-system
      resource: customforms
      verb: GET
  - template:
      apiVersion: core.krateo.io/v1alpha1
      name: finops-example-pricing-vm-azure
      namespace: azure-pricing-system
      resource: compositiondefinitions
      verb: DELETE
  app:
    template:
      color: ${ .getCompositionDefinition.status.conditions[] | select(.type == "Ready") | if .status == "False" then "orange" elif .status == "True" then "green" else "grey" end }
      content: This is a card for FinOps Example Pricing for Azure template (custom form)
      icon: fa-hand-holding-dollar
      tags: azure-pricing-system,0.1.4
      title: FinOps Example Pricing for Azure 
      status: ${ .getCompositionDefinition.status.conditions[] | select(.type == "Ready") | "Ready:" + .status }
      date: ${ .getCompositionDefinition.metadata.creationTimestamp }
      additionalButtonLabel: "Pricing"
      additionalDrawerTitle: "Pricing"
      additionalDrawerContent: ${ .getPricingInformation.status | "Pricing information:\n \(to_entries | map(" up to \(.value)$ per \(.key); ") | join("\n "))" }
  propsRef:
    name: template-finops-example-pricing-vm-azure-card
    namespace: azure-pricing-system
  type: card
  api:
  - name: getCompositionDefinition
    path: "/apis/core.krateo.io/v1alpha1/namespaces/azure-pricing-system/compositiondefinitions/finops-example-pricing-vm-azure"
    verb: GET
    headers:
    - 'Accept: application/json'
  - name: getPricingInformation
    path: "/call?apiVersion=templates.krateo.io%2Fv1&resource=restactions&name=get-pricing-information-frontend&namespace=azure-pricing-system"
    verb: GET
    endpointRef:
      name: snowplow-endpoint
      namespace: krateo-system
    headers:
    - 'Accept: application/json'
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: template-finops-example-pricing-vm-azure-customform
  namespace: azure-pricing-system
data:
  onSubmitId: submit
  onSubmitVerb: POST
  payloadFormKey: spec
  redirectRoute: /compositions/${metadata.namespace}/${metadata.name}
  redirectTimeout: "50"
---
apiVersion: templates.krateo.io/v1alpha1
kind: CustomForm
metadata:
  name: template-finops-example-pricing-vm-azure-customform
  namespace: azure-pricing-system
spec:
  type: customform
  propsRef:
    name: template-finops-example-pricing-vm-azure-customform
    namespace: azure-pricing-system
  actions:
    - template:
        id: submit
        apiVersion: composition.krateo.io/v0-1-4
        verb: POST
        resource: finopsexamplepricingvmazures
        payloadToOverride:
        - name: metadata.name
          value: ${ name }
        - name: metadata.namespace
          value: ${ "azure-pricing-system" }
  app:
    template:
      schema: ${ .getCRD | .spec.versions[] | select(.name == "v0-1-4") | .schema.openAPIV3Schema.properties.spec.properties }
  api:
  - name: getCRD
    path: "/apis/apiextensions.k8s.io/v1/customresourcedefinitions/finopsexamplepricingvmazures.composition.krateo.io"
    verb: GET
    headers:
    - 'Accept: application/json'
---
apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  name: get-pricing-information-frontend
  namespace: azure-pricing-system
spec:
  api:
  - name: getCompositionDefinition
    path: "/apis/core.krateo.io/v1alpha1/namespaces/azure-pricing-system/compositiondefinitions/finops-example-pricing-vm-azure"
    verb: GET
    headers:
    - 'Accept: application/json'
    filter: .metadata.uid
  - name: getPricingInformation
    endpointRef: 
      name: finops-database-handler-endpoint
      namespace: krateo-system
    path: "/compute/pricing_frontend"
    verb: POST
    payload: |
      ${ {composition_id: .getCompositionDefinition} }
    headers:
    - 'Accept: application/json'
    - 'Content-Type: application/json'
    filter: .
  filter: .getPricingInformation