kind: Button
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: finops-template-panel-button
  namespace: finops-system
spec:
  widgetData:
    icon: fa-trash
    type: default
    shape: circle
    clickActionId: cleanup
  actions:
    rest:
      - id: cleanup
        resourceRefId: cleanup
        type: rest
        onSuccessNavigateTo: /templates
  resourcesRefs:
    - id: cleanup
      apiVersion: templates.krateo.io/v1
      resource: restactions
      name: finops-template-restaction-cleanup
      namespace: azure-pricing-system
      verb: GET